### ISSUE TITLE
Fix teleports

### ISSUE THREAD

**Issue by Dune-jr** [Dune-jr/teeworlds#45]

**Comment by Dune-jr** [comment]
https://github.com/Dune-jr/teeworlds/commit/95aee788e0722f4cf3f0107b887b6dc8debdca7b and https://github.com/Dune-jr/teeworlds/commit/687b1cc7a7a4301913ad3200ca6e3a78217719fc may fix it

**Comment by TeeSlayer** [comment]
Yes, I made a few tests and it appears to be fixed. :+1:
