### ISSUE TITLE
Allow True 64 Player support

### ISSUE THREAD

**Issue by AssassinTee** [Dune-jr/teeworlds#79]
Currently you only allow 16 players ingame and  all others are spectators.
This may be fine for pure servers, but with the most visited ones
I could do an easy pull request, since you just need to change one (or two) files.

Edit: This is ment for the DDRace branch, but could be applied to all other modded tw versions

**Comment by Dune-jr** [comment]
Oh, did I not change that on the original release? That's an oversight.
You can PR ddr if you find the time :)

**Comment by Dune-jr** [comment]
https://github.com/Dune-jr/teeworlds/blob/eebba5e822dc1c2a83ba9dedf0021c8a1966e02a/src/game/variables.h#L117

Looks like it's using `MAX_CLIENTS` and not `MAX_PLAYERS`.

**Comment by AssassinTee** [comment]
:o

**Comment by Dune-jr** [comment]
So I guess it's fine.
